[package]
name = "set7"
version = "0.0.1"

[lib]
name = "set7"
path = "lib.rs"

[profile.test]
opt-level = 3

[dependencies.set1]
path = "../set1"

[dependencies.set2]
path = "../set2"

[dependencies.md4_crypto]
path = "./md4_crypto"

[dependencies]
flate2 = "0.2"
rand = "0.3"
