[package]
name = "set6"
version = "0.0.1"

[lib]
name = "set6"
path = "lib.rs"

[dependencies.set1]
path = "../set1"

[dependencies.set5]
path = "../set5"

[dependencies]
itertools = "0.4.13"
ramp = "0.2.4"
rand = "0.3"
