[package]
name = "set5"
version = "0.0.1"

[lib]
name = "set5"
path = "lib.rs"

[dependencies.set1]
path = "../set1"

[dependencies.set2]
path = "../set2"

[dependencies]
rand = "0.3"
rust-crypto = "0.2"
ramp = "0.3"
